# Generated by Django 2.2 on 2021-07-31 04:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login_app', '0002_auto_20210731_0403'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='email',
            new_name='EmailField',
        ),
    ]
